# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20191011_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='notes go here', max_length=255),
            preserve_default=False,
        ),
    ]
